baseURL: http://halo.rebotgpt.top/
languageCode: en-us
title: halo的博客
theme: 2 #  writing / yuguo / 1 / 2
paginate: 9 # 首页文章显示个数
summaryLength: 1000000 # 首页文章摘要字数
hasCJKLanguage: true

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2 # 从 h2 开始
    endLevel: 3 # 到 h4 结束
    ordered: false # 生成 ul 而不是 ol

outputs:
  home:
    - HTML
    - RSS
    - JSON

permalinks:
  blog: /blog/:slug.html/ # 文章输出 url 格式

params:
  title: halo的博客
  description: 无人扶我青云志，我自踏雪至山巅。一名 Web 前端开发工程师，热爱生活。
  logo: https://raw.githubusercontent.com/yangdinghui/Code-Guide/master/pic/46334335 # 博主头像
  author: halo # 博主昵称
  favicon: https://raw.githubusercontent.com/yangdinghui/Code-Guide/master/pic/icons-cat.gif # 网站 favicon 图标
  buildDate: 2024-10-12 # 建站日期
  
  socials: # 导航
    # - name: 标签
    #   link: /tags/
    # - name: 博客
    #   link: /blog/
    # - name: 周刊
    #   link: /categories/weekly/
    # - name: 项目
    #   link: /projects/
    - name: 留言
      link: /message/
    - name: 搜索
      link: /search