baseURL: https://halo.rebotgpt.top/
languageCode: en-us
title: halo的博客
theme: 1 #  writing / yuguo / 1 / txt
paginate: 7 # 首页文章显示个数
summaryLength: 1000000 # 首页文章摘要字数
hasCJKLanguage: true

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2 # 从 h2 开始
    endLevel: 3 # 到 h4 结束
    ordered: false # 生成 ul 而不是 ol

outputs:
  home:
    - HTML
    - RSS
    - JSON

permalinks:
  blog: /blog/:slug.html/ # 文章输出 url 格式

params:
  title: halo的博客
  logo:  https://imgurl.zishu.me/author.webp # 博主头像
  author: halo # 博主昵称
  favicon:  https://imgurl.zishu.me/favicon.ico # 网站 favicon 图标
  buildDate: 2024-10-12 # 建站日期
  
  socials: # 导航
    - name: 技术
      link: /categories/技术/
    - name: 随笔
      link: /categories/随笔/
    # - name: 周刊
    #   link: /categories/weekly/
    # - name: 项目
    #   link: /projects/
    - name: 留言
      link: /message/
    - name: 关于
      link: /about/
services:
  disqus:
    shortname: halo8     